version: "2"
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 100
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
    mass_threshold: 30
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
- "client/__mocks__/"
- "client/_test_/"
- "client/build/"
- "**/coverage/"
- "**/node_modules/"
- "**/public/"
- "**/*.test.js"
