env:
global:
  - CC_TEST_REPORTER_ID=fc20673fc8126b593ca54e7d310d2ec2c7eb77415f426c072e48af7ac7367d88
language:
  - node_js
node_js:
  - 12
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - nvm install stable
  - npm install
  - cd client
  - npm install
  - cd ..
script:
  - cd client
  - npm test
  - ../cc-test-reporter format-coverage --output ../coverage/codeclimate.jest.json
  - cd ..
