env:
global:
  - CC_TEST_REPORTER_ID=95325b4141034c059f27f080ce9f4bb9ac4837204fe4fd73bb289060ed0c5b2a
  - MOZ_HEADLESS=1
language:
  - node_js
node_js:
  - 12
install:
  - nvm install stable
  - npm install
  - cd client
  - npm install
  - cd ..
script:
  - cd client
  - npm test
  - cd ..
